from API_Controller.Controller import deposit
from API_Controller.Controller import disperse_lottery
from API_Controller.Controller import get_accts_and_whitelist
from API_Controller.Controller import register
from API_Controller.Controller import set_governance_reward_rate
